### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by joshreeder** [pipech/frappe-metabase#1]
bench get-app https://github.com/pipech/frappe-metabase.git metabase_integration 
This errors out.

Should just be:
bench get-app https://github.com/pipech/frappe-metabase.git

**Comment by pipech** [comment]
It should be.

    bench get-app metabase_integration https://github.com/pipech/frappe-metabase.git

Updated on readme.md

Thanks and sorry for 4 months late reply.
